### PR TITLE
Fix a reST markup issue

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by vstinner** [comment]
Merged, thanks!

**Comment by Mariatta** [comment]
🤔  When I go to http://asyncio.readthedocs.io/en/latest/why_asyncio.html, the url is still not properly linked. Screenshot:

screen shot 2017-05-04 at 10 55 26 pm

**Comment by vstinner** [comment]
On https://readthedocs.org/projects/asyncio/builds/ I see that the last build was done two months ago :-( It seems like the hook from GitHub to ReadTheDocs has issues. On https://twitter.com/githubstatus I regulary see issues with webhooks, can it be related?

Anyway, at least for this commit, I forced a new build.

If someone wants to investigate, give me your ReadTheDocs login. Currently, @brettcannon and me are maintainers of https://readthedocs.org/dashboard/asyncio/users/

I can also give you access to the GitHub project if you want. Sadly, the only configuration is the webhook configured in GitHub and it's still there...

**Comment by brettcannon** [comment]
Maybe try removing and adding the Read the Docs hook again?

**Pull request merged**
