### PR TITLE
added info on known bug in asyncio

### PR DESCRIPTION
**Pull request by mentaal**
on Windows affecting KeyboardInterrupt

### CODE REVIEW

**Comment by mentaal** [comment]
@GMLudo is this PR ok?

**Comment by vstinner** [comment]
I don't think that "Getting Started" is the right place for such information.

**Comment by mentaal** [comment]
It tripped me up as I'm on Windows. I mean I was "getting started" and immediately had this problem

**Comment by mentaal** [comment]
It tripped me up as I'm on Windows. I mean I was "getting started" and immediately had this problem

**Pull request closed without merging**
